apiVersion: v1
kind: Secret
metadata:
  name: airbyte-auth-secrets
type: Opaque
stringData:
  instance-admin-password: "${AIRBYTE_ADMIN_PASSWORD}"
  instance-admin-client-id: "${AIRBYTE_CLIENT_ID}"
  instance-admin-client-secret: "${AIRBYTE_CLIENT_SECRET}"
