from pyspark.sql import DataFrame
from pyspark.sql.functions import col


def transform(df: DataFrame) -> DataFrame:
    return df.select(
        col("advertiser_id").cast("string").alias("ad_account_id"),
        col("campaign_id").cast("string").alias("campaign_id"),
        col("campaign_name"),
        col("adgroup_id").cast("string").alias("ad_group_id"),
        col("adgroup_name").alias("ad_group_name"),
        col("ad_id").cast("string").alias("ad_id"),
        col("ad_name"),
        col("image_ids"),
        col("call_to_action"),
        col("call_to_action_id").cast("string").alias("call_to_action_id"),
        col("secondary_status"),
        col("operation_status"),
        col("is_aco"),
        col("ad_format"),
        col("ad_text"),
        col("video_id").cast("string").alias("video_id"),
        col("tiktok_item_id").cast("string").alias("tiktok_item_id"),
        col("app_name"),
        col("display_name"),
        col("profile_image_url"),
        col("tracking_pixel_id").cast("string").alias("tracking_pixel_id"),
        col("deeplink"),
        col("deeplink_type"),
        col("fallback_type"),
        col("playable_url"),
        col("vast_moat_enabled"),
        col("creative_authorized"),
        col("is_new_structure"),
        col("create_time"),
        col("modify_time"),
        col("promotional_music_disabled"),
        col("avatar_icon_web_uri"),
        col("brand_safety_postbid_partner"),
        col("identity_id").cast("string").alias("identity_id"),
        col("identity_type"),
        col("optimization_event"),
        col("viewability_postbid_partner"),
        col("_airbyte_raw_id"),
        col("_airbyte_extracted_at"),
        col("_airbyte_meta"),
    )
