from pyspark.sql import DataFrame
from pyspark.sql.functions import col


def transform(df: DataFrame) -> DataFrame:
    return df.select(
        col("metrics.campaign_id").cast("string").alias("campaign_id"),
        col("metrics.adgroup_id").cast("string").alias("ad_group_id"),
        col("ad_id").cast("string").alias("ad_id"),
        col("stat_time_day"),
        col("metrics.impressions").cast("integer").alias("impressions"),
        col("metrics.real_time_cost_per_conversion")
        .cast("Decimal(10,2)")
        .alias("real_time_cost_per_conversion"),
        col("metrics.mobile_app_id").cast("string").alias("mobile_app_id"),
        col("metrics.ctr").cast("Decimal(10,2)").alias("ctr"),
        col("metrics.conversion_rate").cast("Decimal(10,2)").alias("conversion_rate"),
        col("metrics.tt_app_id"),
        col("metrics.real_time_conversion_rate")
        .cast("Decimal(10,2)")
        .alias("real_time_conversion_rate"),
        col("metrics.conversion").cast("integer").alias("conversion"),
        col("metrics.ad_text"),
        col("metrics.cost_per_conversion")
        .cast("Decimal(10,2)")
        .alias("cost_per_conversion"),
        col("metrics.cpc").cast("Decimal(10,2)").alias("cpc"),
        col("metrics.real_time_cost_per_result")
        .cast("Decimal(10,2)")
        .alias("real_time_cost_per_result"),
        col("metrics.result_rate").cast("Decimal(10,2)").alias("result_rate"),
        col("metrics.clicks").cast("integer").alias("clicks"),
        col("metrics.result").cast("integer").alias("result"),
        col("metrics.placement_type"),
        col("metrics.promotion_type"),
        col("metrics.tt_app_name"),
        col("metrics.spend").cast("Decimal(10,2)").alias("spend"),
        col("metrics.cost_per_result").cast("Decimal(10,2)").alias("cost_per_result"),
        col("metrics.real_time_conversion").cast("integer").alias("real_time_conversion"),
        col("metrics.real_time_result").cast("integer").alias("real_time_result"),
        col("metrics.cpm").cast("Decimal(10,2)").alias("cpm"),
        col("metrics.real_time_result_rate")
        .cast("Decimal(10,2)")
        .alias("real_time_result_rate"),
        col("metrics.cost_per_total_sales_lead")
        .cast("Decimal(10,2)")
        .alias("cost_per_total_sales_lead"),
        col("metrics.purchase").cast("integer").alias("purchase"),
        col("metrics.cost_per_sales_lead")
        .cast("Decimal(10,2)")
        .alias("cost_per_sales_lead"),
        col("metrics.registration_rate").cast("Decimal(10,2)").alias("registration_rate"),
        col("metrics.cost_per_1000_reached")
        .cast("Decimal(10,2)")
        .alias("cost_per_1000_reached"),
        col("metrics.clicks_on_music_disc").cast("integer").alias("clicks_on_music_disc"),
        col("metrics.vta_purchase").cast("integer").alias("vta_purchase"),
        col("metrics.frequency").cast("Decimal(10,2)").alias("frequency"),
        col("metrics.purchase_rate").cast("Decimal(10,2)").alias("purchase_rate"),
        col("metrics.shares").cast("integer").alias("shares"),
        col("metrics.total_purchase_value")
        .cast("Decimal(10,2)")
        .alias("total_purchase_value"),
        col("metrics.cost_per_registration")
        .cast("Decimal(10,2)")
        .alias("cost_per_registration"),
        col("metrics.comments").cast("integer").alias("comments"),
        col("metrics.app_install").cast("integer").alias("app_install"),
        col("metrics.complete_payment").cast("integer").alias("complete_payment"),
        col("metrics.profile_visits_rate")
        .cast("Decimal(10,2)")
        .alias("profile_visits_rate"),
        col("metrics.average_video_play").cast("Decimal(10,2)").alias("average_video_play"),
        col("metrics.profile_visits").cast("integer").alias("profile_visits"),
        col("metrics.value_per_complete_payment")
        .cast("Decimal(10,2)")
        .alias("value_per_complete_payment"),
        col("metrics.total_app_event_add_to_cart")
        .cast("integer")
        .alias("total_app_event_add_to_cart"),
        col("metrics.average_video_play_per_user")
        .cast("Decimal(10,2)")
        .alias("average_video_play_per_user"),
        col("metrics.cost_per_total_app_event_add_to_cart")
        .cast("Decimal(10,2)")
        .alias("cost_per_total_app_event_add_to_cart"),
        col("metrics.cost_per_app_install")
        .cast("Decimal(10,2)")
        .alias("cost_per_app_install"),
        col("metrics.registration").cast("integer").alias("registration"),
        col("metrics.reach").cast("integer").alias("reach"),
        col("metrics.sales_lead_rate").cast("Decimal(10,2)").alias("sales_lead_rate"),
        col("metrics.sales_lead").cast("integer").alias("sales_lead"),
        col("metrics.total_complete_payment_rate")
        .cast("Decimal(10,2)")
        .alias("total_complete_payment_rate"),
        col("metrics.total_onsite_shopping_value")
        .cast("Decimal(10,2)")
        .alias("total_onsite_shopping_value"),
        col("metrics.video_views_p100").cast("integer").alias("video_views_p100"),
        col("metrics.video_views_p75").cast("integer").alias("video_views_p75"),
        col("metrics.video_watched_2s").cast("integer").alias("video_watched_2s"),
        col("metrics.video_watched_6s").cast("integer").alias("video_watched_6s"),
        col("metrics.video_views_p50").cast("integer").alias("video_views_p50"),
        col("metrics.video_views_p25").cast("integer").alias("video_views_p25"),
        col("metrics.video_play_actions").cast("integer").alias("video_play_actions"),
        col("metrics.onsite_shopping").cast("integer").alias("onsite_shopping"),
        col("metrics.real_time_app_install")
        .cast("Decimal(10,2)")
        .alias("real_time_app_install"),
        col("metrics.real_time_app_install_cost")
        .cast("Decimal(10,2)")
        .alias("real_time_app_install_cost"),
        col("metrics.cost_per_purchase").cast("Decimal(10,2)").alias("cost_per_purchase"),
        col("_airbyte_raw_id"),
        col("_airbyte_extracted_at"),
        col("_airbyte_meta"),
    )
